#spring.data.mongodb.uri=mongodb+srv://duongquangdat:quangdat@myserver.ruqy4gt.mongodb.net/?retryWrites=true&w=majority&appName=MyServer
#spring.data.mongodb.database=chinese-chess
spring:
  data:
    mongodb:
      uri: mongodb+srv://duongquangdat:quangdat@myserver.ruqy4gt.mongodb.net/?retryWrites=true&w=majority&appName=MyServer
      database: chinese-chess
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 825569252266-948mbvjhosq3ue5dvgk5679dvu2mssse.apps.googleusercontent.com
            client-secret: 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


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000